/**
 * Pulls the catalog from the connected Shopify store (Storefront API) and
 * writes lib/shopify-variants.json: our option id (= variant SKU) → variant
 * GID. Checkout uses that map to build Shopify carts. Also warns when a
 * Shopify price has drifted from the storefront's displayed price, and when
 * products/variants are missing on either side.
 *
 * Run after the CSV import, and after any product change in Shopify:
 *   npm run shopify:sync   (reads NEXT_PUBLIC_SHOPIFY_* from .env.local)
 * Then commit lib/shopify-variants.json and redeploy.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { products } from "../../lib/data";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");

// Minimal .env.local loader (no dependency on Next's env pipeline).
for (const file of [".env.local", ".env"]) {
  const p = join(root, file);
  if (!existsSync(p)) continue;
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (m && process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
    }
  }
}

const DOMAIN = process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN?.trim();
const TOKEN = process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN?.trim();
if (!DOMAIN || !TOKEN) {
  console.error(
    "Set NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN and NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN in .env.local first.",
  );
  process.exit(1);
}

const QUERY = /* GraphQL */ `
  query Catalog($cursor: String) {
    products(first: 100, after: $cursor) {
      pageInfo { hasNextPage endCursor }
      nodes {
        handle
        variants(first: 20) {
          nodes {
            id
            sku
            price { amount }
          }
        }
      }
    }
  }
`;

type CatalogPage = {
  products: {
    pageInfo: { hasNextPage: boolean; endCursor: string | null };
    nodes: {
      handle: string;
      variants: { nodes: { id: string; sku: string; price: { amount: string } }[] };
    }[];
  };
};

async function fetchPage(cursor: string | null): Promise<CatalogPage> {
  const res = await fetch(`https://${DOMAIN}/api/2025-07/graphql.json`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Shopify-Storefront-Access-Token": TOKEN!,
    },
    body: JSON.stringify({ query: QUERY, variables: { cursor } }),
  });
  const json = (await res.json()) as { data?: CatalogPage; errors?: { message: string }[] };
  if (!res.ok || json.errors?.length || !json.data) {
    throw new Error(json.errors?.[0]?.message ?? `HTTP ${res.status}`);
  }
  return json.data;
}

const variants: Record<string, string> = {};
const shopifyPriceBySku: Record<string, number> = {};
const shopifyHandles = new Set<string>();

let cursor: string | null = null;
for (;;) {
  const page: CatalogPage = await fetchPage(cursor);
  for (const product of page.products.nodes) {
    shopifyHandles.add(product.handle);
    for (const v of product.variants.nodes) {
      if (!v.sku) continue;
      variants[v.sku] = v.id;
      shopifyPriceBySku[v.sku] = Number(v.price.amount);
    }
  }
  if (!page.products.pageInfo.hasNextPage) break;
  cursor = page.products.pageInfo.endCursor;
}

// Reconcile against the storefront catalog.
let missingVariants = 0;
let priceDrift = 0;
for (const p of products) {
  if (!shopifyHandles.has(p.slug)) {
    console.warn(`!! product missing in Shopify: ${p.slug}`);
  }
  for (const option of p.options) {
    const gid = variants[option.id];
    if (!gid) {
      missingVariants++;
      console.warn(`!! no Shopify variant with SKU "${option.id}" (${p.name})`);
      continue;
    }
    const shopifyPrice = shopifyPriceBySku[option.id];
    if (Math.abs(shopifyPrice - option.priceUsd) > 0.001) {
      priceDrift++;
      console.warn(
        `!! price drift ${option.id}: site shows $${option.priceUsd.toFixed(2)}, Shopify charges $${shopifyPrice.toFixed(2)}`,
      );
    }
  }
}

const outFile = join(root, "lib/shopify-variants.json");
writeFileSync(
  outFile,
  JSON.stringify(
    {
      _comment:
        "Generated by `npm run shopify:sync` — maps internal option ids (Shopify variant SKUs) to Storefront variant GIDs.",
      variants,
    },
    null,
    2,
  ) + "\n",
  "utf8",
);

console.log(
  `Wrote ${Object.keys(variants).length} variant mappings to lib/shopify-variants.json` +
    ` (${missingVariants} missing, ${priceDrift} price drift warnings).`,
);
if (missingVariants === 0 && priceDrift === 0) {
  console.log("✓ Shopify catalog matches the storefront. Commit the JSON and deploy.");
}
